### ISSUE TITLE
TypeError: iteration over non-sequence

### ISSUE THREAD

**Issue by chmielu** [erdbeere/tml#13]
```
tml $ python2 tml.py 
Traceback (most recent call last):
  File "tml.py", line 452, in <module>
    t.save()
  File "tml.py", line 301, in save
    image_data = image.get_data(len(datas))
  File "/home/chmielu/Projekty/tml/tml/items.py", line 176, in get_data
    for i in self.image:
TypeError: iteration over non-sequence
```

**Comment by SushiTee** [comment]
Invalid
